### PR TITLE
fix(deploy, package): propagate non-zero exit codes

### LINKED ISSUE #178: Non-Zero exit code gets lost while shelling out to `aws cloudformation`
`sam package` and `sam local` swallow the exit code of the underlying `aws cloudformation` command. In case of an error they forward stderr but they still exit with `0`.

I'm not much of a gopher but for me it looks like the exit code would be returned [here](https://github.com/awslabs/aws-sam-local/blob/72b724f6aade27a0fd81fb23b02101bccacfda2e/package.go#L36) so one could probably just call `os.Exit()` with the result if this isn't zero?

### PR DESCRIPTION
**Pull request by Fahrradflucht**
Because the err returned by `cmd.Wait()` wasn't checked `sam package` and `sam
deploy` would always return exit code 0 even if the aws cli cmd had a non-zero
exit code.

This commit checks the error and calls `log.Fatal()`. While this prints the
original exit code to stderr (at least on macOS) this does not propagate the
original error code but exits with 1. This is because there seems to be no easy
os independent way of getting the exit code. Anyway this should do it for all
sane use cases.

Closes #178

### CODE REVIEW

File: deploy.go [hunk 1]
```diff
@@ -33,6 +33,7 @@ func deploy() {
 	go io.Copy(os.Stderr, stderr)
 	go io.Copy(os.Stdout, stdout)
 
-	cmd.Wait()
-
+	if err := cmd.Wait(); err != nil {
+		log.Fatal(err)
```
Comment (sanathkr) [inline deploy.go]: can't you just exit with os.exit(1) instead? It might not be much use printing the `err` object which is a Go-specific data structure.

Comment (Fahrradflucht) [reply deploy.go]: Done

**Comment by PaulMaddox** [comment]
Thanks for making those changes @Fahrradflucht. Merging this now.
