### PR TITLE
Fixed runtime container working directory bug

### LINKED ISSUE #22: create .: volume name is too short, names should be at least two alphanumeric characters
When I am trying to run function locally I got error form docker:

```
sam local invoke "HelloWorldFunction" -e index.js
2017/08/12 13:03:27 0.1.0
2017/08/12 13:03:27 Successfully parsed template.yaml (version 2010-09-09)
2017/08/12 13:03:27 Connected to Docker 1.30
2017/08/12 13:03:27 Fetching lambci/lambda:nodejs4.3 image for nodejs4.3 runtime...
nodejs4.3: Pulling from lambci/lambda
Digest: sha256:1ec74ee2e5c71e231d87d9b961f4f310bf817088f4391763a37e5adb657c6038
Status: Image is up to date for lambci/lambda:nodejs4.3
2017/08/12 13:03:30 Invoking index.handler (nodejs4.3)
2017/08/12 13:03:30 Could not invoke function: Error response from daemon: create .: volume name is too short, names should be at least two alphanumeric characters
```

Some info about my local system:
```
docker -v
Docker version 17.06.0-ce, build 02c1d87
```
```
docker-compose -v
docker-compose version 1.14.0, build c7bdf9e
```

OS
```
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
```

pls let me know in case if you need more info

### PR DESCRIPTION
**Pull request by PaulMaddox**
Fixed runtime container working directory that caused it to be an empty string if the CodeUri was set to something that wasn't a valid directory.

Wrote a load of test cases for working directory related stuff to prevent future regressions.

Fixes #22

```
Running Suite: AwsSamLocal Suite
================================
Random Seed: 1503044376
Will run 52 of 52 specs

••••••••••••••••••••••••••••••••••••••••••••••••••••
Ran 52 of 52 Specs in 0.018 seconds
SUCCESS! -- 52 Passed | 0 Failed | 0 Pending | 0 Skipped PASS

Ginkgo ran 1 suite in 1.255006227s
Test Suite Passed
```

### CODE REVIEW

File: runtime.go [hunk 1]
```diff
@@ -584,7 +584,7 @@ func getWorkingDir(basedir string, codeuri string, checkWorkingDirExist bool) (s
 		if _, err := os.Stat(dir); err != nil {
 			// It doesn't, so just use the directory of the SAM template
 			// which might have been passed as a relative directory
-			dir = basedir
+			dir = abs
```
Comment (PaulMaddox) [inline runtime.go]: This was the cause of the bug. 
If the base directory was empty (e.g. if they called --template filename.yaml), and the CodeUri wasn't a valid relative directory that exists, then instead of returning the current working directory, it returned "".

**Comment by sanathkr** [comment]
Travis build 👍🏼
